spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db
    username: sa
    password:

  h2:
    console:
      enabled: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
